# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_wq2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WQ',
        ),
        migrations.DeleteModel(
            name='WQ1',
        ),
        migrations.DeleteModel(
            name='WQ2',
        ),
    ]
